[package]
name = "silver-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.2"
num = "0.4.3"
indexmap = "2.9.0"
petgraph = "0.6.5"
internment = { git = "https://github.com/JonasAlaif/internment", default-features = false, features = ["std", "bump"] }

typed-index-collections = "3.2.3"
nonmax = "0.5"
