[package]
name = "silver-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.2"
num-bigint = "0.4.6"
fxhash = "0.2.1"
