[package]
name = "silver-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
peg = "0.8.2"
pest = "2.7.9"
pest_derive = "2.7.9"
